# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

arr =np.array([0,1,2,3,4,5,6,7,8,9]) 
arr = np.reshape(arr,(2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
import numpy as np
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1,]])
arr3=np.vstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
import numpy as np
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1,]])
arr3=np.hstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
import numpy as np
arr = np.arange(10).reshape(1,2,5)
arr = arr.flatten()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
import numpy as np
arr = np.arange(15).reshape(1,3,5)
arr=arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
import numpy as np
arr = np.arange(15)
arr = arr.reshape(-1,5,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
import numpy as np
arr = np.arange(25).reshape(5,5)
arr = np.square(arr)
arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
import numpy as np
arr = np.arange(30).reshape(5,6)
arr = np.mean(arr)
arr

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
import numpy as np
arr = np.arange(30).reshape(5,6)
arr = np.std(arr)
arr


8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
import numpy as np
arr = np.arange(30).reshape(5,6)
arr = np.median(arr)
arr

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
import numpy as np
arr = np.arange(30).reshape(5,6)
arr = np.transpose(arr)
arr

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
import numpy as np
arr = np.arange(16).reshape(4,4)
arr = np.trace(arr)
arr

30

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
import numpy as np
arr = np.arange(16).reshape(4,4)
arr = np.linalg.det(arr)
arr

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
import numpy as np
arr = np.arange(16).reshape(4,4)
v1 = np.percentile(arr,5)
v2 = np.percentile(arr,95)
print ("5th :",v1,"9th :",v2)


5th : 0.75 9th : 14.25


## Question:15

### How to find if a given array has any null values?

In [15]:
import numpy as np
arr = np.array([[1,2,3,4,5,5,6],[9,8,7,np.nan,5,4,3]])
arr = np.sum(arr)
arr = np.isnan(arr)
arr

True